CREATE SCHEMA AUTHORIZATION CMSTR

CREATE TABLE "TBL_MEMBER_MASTER" 
   (  "MEM_ID" NUMBER(19,0) NOT NULL ENABLE, 
  "CIN" VARCHAR2(255 CHAR), 
  "CLEARING_MEM_ID" VARCHAR2(255 CHAR), 
  "CONSTITUTION_TYPE" VARCHAR2(255 CHAR), 
  "EMAIL_ID" VARCHAR2(255 CHAR), 
  "FULL_STATUS" VARCHAR2(255 CHAR), 
  "FULL_STATUS_UPDATE_TIME" TIMESTAMP (6), 
  "MEM_ADDRESS_PART1" VARCHAR2(255 CHAR), 
  "MEM_ADDRESS_PART2" VARCHAR2(255 CHAR), 
  "MEM_ADDRESS_PART3" VARCHAR2(255 CHAR), 
  "MEM_APPLICATION_DATE" TIMESTAMP (6), 
  "MEM_APPROVAL_DATE" TIMESTAMP (6), 
  "MEM_CD" VARCHAR2(255 CHAR), 
  "MEM_CENTRE" VARCHAR2(255 CHAR), 
  "MEM_CONTACT_NUM" VARCHAR2(255 CHAR), 
  "MEM_CREATED_BY_USER" VARCHAR2(255 CHAR), 
  "MEM_CREATED_DATE" TIMESTAMP (6), 
  "MEM_ENTITY_TYPE" VARCHAR2(255 CHAR), 
  "MEM_NAME" VARCHAR2(255 CHAR), 
  "MEM_PAN_NUM" VARCHAR2(255 CHAR), 
  "TYPE" VARCHAR2(255 CHAR), 
  "SEBI_REGISTRATION_NUM" VARCHAR2(255 CHAR), 
  "SEBI_REGISTRATION_NUM_PART_1" VARCHAR2(255 CHAR), 
  "SEBI_REGISTRATION_NUM_PART_2_MEM" VARCHAR2(255 CHAR), 
  "SEBI_REGISTRATION_NUM_PART_3" VARCHAR2(255 CHAR), 
  "SEBI_REGISTRATION_NUM_PART_4" VARCHAR2(255 CHAR), 
  "SYS_AUDIT_ADVERSE" VARCHAR2(255 CHAR), 
  "SYS_ENTITY_INSPECT" VARCHAR2(255 CHAR), 
  "SYS_IRREGULARITIES" VARCHAR2(255 CHAR), 
  "SYSTEM_COMPLY_SEBI" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("MEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

CREATE TABLE "TBL_USER_MEM_COM" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "EMAIL_ID" VARCHAR2(255 CHAR), 
  "FIRST_NAME" VARCHAR2(255 CHAR), 
  "HO" VARCHAR2(255 CHAR), 
  "LAST_NAME" VARCHAR2(255 CHAR), 
  "RO" VARCHAR2(255 CHAR), 
  "USER_TYPE" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

CREATE TABLE "TBL_VERIFICATION_DETAILS" 
   ( 
  "VERIFY_ID" NUMBER(19,0) NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "NAME" VARCHAR2(255 CHAR), 
  "REASON" VARCHAR2(255 CHAR), 
  "VERIFIED_FLAG" NUMBER(1,0), 
  "VERIFIED_STATUS" VARCHAR2(255 CHAR), 
  "VERIFY_ENTITY" VARCHAR2(255 CHAR), 
  "VERIFY_TYPE" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("VERIFY_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

CREATE TABLE "TBL_AIML_SYSTEM_DETAILS" 
   (  
  "APP_SYSTEM_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "TOOLS_TECHNOLOGY_CATEGORY" VARCHAR2(255 CHAR), 
  "APP_SYSTEM_CYBER_SECURITY" VARCHAR2(255 CHAR), 
  "APP_SYSTEM_NAME" VARCHAR2(255 CHAR), 
  "APP_SYSTEM_PRODUCT_OFFER" VARCHAR2(255 CHAR), 
  "APP_SYSTEM_USED" VARCHAR2(255 CHAR), 
  "APP_SYSTEM_USED_DATE" TIMESTAMP (6), 
  "AREA_TYPE_AIML_USED" VARCHAR2(255 CHAR), 
  "CICULAR_SEBI_SECURITY_CONTROL" VARCHAR2(255 CHAR), 
  "CLAIM_AIML_APP_SYSTEM" VARCHAR2(255 CHAR), 
  "CONTROL_POINTS" VARCHAR2(255 CHAR), 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "MEMBER_ID" NUMBER(19,0), 
  "PROJECT_IMPLEMENTED" VARCHAR2(255 CHAR), 
  "QUARTER" VARCHAR2(255 CHAR), 
  "SAFEGUARD_APP" VARCHAR2(255 CHAR), 
  "SYS_TYPE" VARCHAR2(255 CHAR), 
  "SYSTEM_COMPLY_SEBI" VARCHAR2(255 CHAR), 
  "SYSTEM_DISSEMINATE" VARCHAR2(255 CHAR), 
  "SYSTEM_FALLS_DI_PM" VARCHAR2(255 CHAR), 
  "SYSTEM_INCLUDE_AUDIT" VARCHAR2(255 CHAR), 
  "SYSTEM_INVOLVES_ORDER" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("APP_SYSTEM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

CREATE TABLE "MEMBER_AIML_DTL" 
   (  "ID" NUMBER(19,0) NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "ELIGIBLE_FLAG" VARCHAR2(255 CHAR), 
  "MEM_CD_SEGMT" VARCHAR2(255 CHAR), 
  "MEM_ID" NUMBER(19,0), 
  "NIL_FLAG" VARCHAR2(255 CHAR), 
  "QUARTER_END_DATE" TIMESTAMP (6), 
  "QUARTER_NAME" VARCHAR2(255 CHAR), 
  "QUARTER_START_DATE" TIMESTAMP (6), 
  "SUBMISSION_DONE" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

CREATE TABLE "TBL_ADDRESS_KMP"
   (	
  "ID" NUMBER(19,0) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_DT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"UPDATED_DT" TIMESTAMP (6), 
	"ADDRESS_LINE1" VARCHAR2(255 CHAR), 
	"ADDRESS_LINE2" VARCHAR2(255 CHAR), 
	"ADDRESS_LINE3" VARCHAR2(255 CHAR), 
	"ADDRESS_LINE4" VARCHAR2(255 CHAR), 
	"ADDRESS_LINE5" VARCHAR2(255 CHAR), 
	"ADDRESS_LINE6" VARCHAR2(255 CHAR), 
	"CITY" VARCHAR2(255 CHAR), 
	"DISTRICT" VARCHAR2(255 CHAR), 
	"PINCODE" NUMBER(10,0), 
	"STATE" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

  CREATE TABLE "TBL_DOCUMENT_UPLOAD_KMP"
   (	"ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_DT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"UPDATED_DT" TIMESTAMP (6), 
	"APP_ID" VARCHAR2(255 CHAR), 
	"DOC_INDEX" NUMBER(19,0), 
	"DOC_TYPE" VARCHAR2(255 CHAR), 
	"EXTENTION" VARCHAR2(255 CHAR), 
	"FILE_DATA" BLOB, 
	"FILE_NAME" VARCHAR2(255 CHAR), 
	"FILE_SIZE" NUMBER(19,0), 
	"FILE_URL" VARCHAR2(255 CHAR), 
	"FOLDER_INDEX" NUMBER(19,0), 
	"MEMBER_ID" NUMBER(19,0), 
	"SUB_REQUEST_TYPE" VARCHAR2(255 CHAR), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

   CREATE TABLE "TBL_COMPLIANCE_OFFICER_KMP" 
   (	"COMP_ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_DT" TIMESTAMP (6), 
	"UPDATED_BY" VARCHAR2(255 CHAR), 
	"UPDATED_DT" TIMESTAMP (6), 
	"COMP_APPOINTMENTDT" DATE, 
	"COMP_CERTIFICATION_EXAMDT" DATE, 
	"COMP_CERTIFICATION_EXAMTYPE" VARCHAR2(255 CHAR), 
	"COMP_CERTIFICATIONNAME" VARCHAR2(255 CHAR), 
	"COMP_CERTIFICATION_PAN" VARCHAR2(255 CHAR), 
	"COMP_CERTIFICATIONTYPE" VARCHAR2(255 CHAR), 
	"COMP_CERTIFICATION_VALIDTILDT" DATE, 
	"COMP_CERTIFICATION_VALIDATED" VARCHAR2(255 CHAR), 
	"COMP_DECLAREDKMP" VARCHAR2(255 CHAR), 
	"COMP_EMPLOYMENTDT" DATE, 
	"COMP_QUALIFICATION" VARCHAR2(255 CHAR), 
	"COMP_SALUTATION" VARCHAR2(255 CHAR), 
	"COMP_STATUS" NUMBER(10,0), 
	"DIN" NUMBER(19,0), 
	"DOB" DATE, 
	"COMP_EMAIL_ID" VARCHAR2(255 CHAR), 
	"END_DT" DATE, 
	"COMP_MOBILE_NUMBER" VARCHAR2(255 CHAR), 
	"COMP_NAME" VARCHAR2(255 CHAR), 
	"COMP_PAN_NO" VARCHAR2(255 CHAR), 
	"PAN_STATUS" VARCHAR2(255 CHAR), 
	"COMP_PAN_VERIFIED" VARCHAR2(255 CHAR), 
	"COMP_PHONENUMBER" VARCHAR2(255 CHAR), 
	"START_DT" DATE, 
	"COMPLIANCE_OFFICER_TITLE" VARCHAR2(255 CHAR), 
	"COMP_ADDRESSID" NUMBER(19,0), 
	"COMP_CERTIFICATIONDOCID" VARCHAR2(255 CHAR), 
	"MEMBER_ID" NUMBER(19,0), 
    PRIMARY KEY ("COMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
    CONSTRAINT "FKOLE48AB13LOENTKM5M1SJM4S" FOREIGN KEY ("COMP_ADDRESSID")
	  REFERENCES "TBL_ADDRESS_KMP" ("ID") ENABLE,
	 CONSTRAINT "FKLSXV8NTQHK6X39Y3L39W7AJ3J" FOREIGN KEY ("COMP_CERTIFICATIONDOCID")
	  REFERENCES "TBL_DOCUMENT_UPLOAD_KMP" ("ID") ENABLE,
	 CONSTRAINT "FKTAQOXFIFX6N5V2VTQ6TWHVVX0" FOREIGN KEY ("MEMBER_ID")
	  REFERENCES "TBL_MEMBER_MASTER" ("MEM_ID") ENABLE
  );


   CREATE TABLE "TBL_SHAREHOLDER" 
   (  
  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "DIN" NUMBER(19,0), 
  "DOB" DATE, 
  "EMAIL_ID" VARCHAR2(255 CHAR), 
  "END_DT" DATE, 
  "MEM_ID" NUMBER(19,0), 
  "MOBILE_NUMBER" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "PAN_NUMBER" VARCHAR2(255 CHAR), 
  "PAN_STATUS" VARCHAR2(255 CHAR), 
  "PAN_VALIDATED" VARCHAR2(255 CHAR), 
  "PHONE_NUMBER" VARCHAR2(255 CHAR), 
  "START_DT" DATE, 
  "PROPRIETOR_STATUS" VARCHAR2(255 CHAR), 
  "SHAREHOLDER_TITLE" VARCHAR2(255 CHAR), 
  "SHAREHOLDER_TYPE" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

CREATE TABLE "TBL_PARTNER" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "DIN" NUMBER(19,0), 
  "DOB" DATE, 
  "EMAIL_ID" VARCHAR2(255 CHAR), 
  "END_DT" DATE, 
  "MEM_ID" NUMBER(19,0), 
  "MOBILE_NUMBER" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "PAN_NUMBER" VARCHAR2(255 CHAR), 
  "PAN_STATUS" VARCHAR2(255 CHAR), 
  "PAN_VALIDATED" VARCHAR2(255 CHAR), 
  "PHONE_NUMBER" VARCHAR2(255 CHAR), 
  "START_DT" DATE, 
  "PARTNER_STATUS" VARCHAR2(255 CHAR), 
  "PARTNER_TITLE" VARCHAR2(255 CHAR), 
  "PARTNER_TYPE" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

CREATE TABLE "TBL_PROPRIETOR" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "DIN" NUMBER(19,0), 
  "DOB" DATE, 
  "EMAIL_ID" VARCHAR2(255 CHAR), 
  "END_DT" DATE, 
  "MEM_ID" NUMBER(19,0), 
  "MOBILE_NUMBER" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "PAN_NUMBER" VARCHAR2(255 CHAR), 
  "PAN_STATUS" VARCHAR2(255 CHAR), 
  "PAN_VALIDATED" VARCHAR2(255 CHAR), 
  "PHONE_NUMBER" VARCHAR2(255 CHAR), 
  "START_DT" DATE, 
  "PROPRIETOR_STATUS" VARCHAR2(255 CHAR), 
  "PROPRIETOR_TITLE" VARCHAR2(255 CHAR), 
  "PROPRIETOR_TYPE" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

CREATE SEQUENCE id_seq_TBL_DIRECTOR START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;

CREATE TABLE "TBL_DIRECTOR_KMP" 
   ( 
    "ID" NUMBER(30,0) DEFAULT ON NULL id_seq_TBL_DIRECTOR.nextval NOT NULL ENABLE,
    "DIRECTOR_TITLE" VARCHAR2(255 BYTE),
    "DIRECTORID" NUMBER(10,0) NOT NULL ENABLE,
    "NAME" VARCHAR2(100 BYTE),
    "PAN_NUMBER" VARCHAR2(15 BYTE),
    "MOBILE_NUMBER" VARCHAR2(75 BYTE),
    "EMAIL_ID" VARCHAR2(100 BYTE),
    "DOB" DATE,
    "TOTAL_EXPERIENCE" NUMBER(9,0),
    "MEM_ID" NUMBER(10,0) NOT NULL ENABLE,
    "DIN" VARCHAR2(30 BYTE),
    "DIRECTOR_TYPE" VARCHAR2(15 BYTE),
    "E_SIGNATURE" CHAR(1 BYTE),
    "DIR_STATUS" VARCHAR2(10 BYTE),
    "CREATED_BY" VARCHAR2(30 BYTE),
    "CREATED_DT" TIMESTAMP (6) NOT NULL ENABLE,
    "POST_FACTO" CHAR(1 BYTE),
    "NATIONALITY" VARCHAR2(20 BYTE),
    "EDUCATION_QUALIFICATION" VARCHAR2(20 BYTE),
    "UPDATED_BY" VARCHAR2(30 BYTE),
    "UPDATED_DT" TIMESTAMP (6),
    "START_DT" DATE NOT NULL ENABLE,
    "END_DT" DATE NOT NULL ENABLE,
    "PAN_VALIDATED" CHAR(1 BYTE),
    "PAN_STATUS" VARCHAR2(30 BYTE),
    "JOINING_DT" DATE NOT NULL ENABLE,
    "RESIGNING_DT" DATE,
    "ADDRESS_ID" VARCHAR2(10 BYTE),
    "PRIOR_APPROVAL_DT" TIMESTAMP (6),
    "EXTENSION_DT" TIMESTAMP (6),
    "DIR_12" CHAR(1 BYTE),
    "REJECTED_DT" DATE,
    "PHONE_NUMBER" VARCHAR2(255 CHAR),
    PRIMARY KEY ("ID")  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 TABLESPACE "CMSTR_TABLESPACE"  ENABLE,
    CONSTRAINT "FK_KMP_DIR_MEM_ID" FOREIGN KEY ("MEM_ID") REFERENCES "TBL_MEMBER_MASTER" ("MEM_ID") ENABLE
   );

CREATE TABLE "TBL_KMP" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "ACTION" VARCHAR2(255 CHAR), 
  "ACTION_DT" TIMESTAMP (6), 
  "ADDL_DESIGNATION" VARCHAR2(255 CHAR), 
  "APP_ID" NUMBER(19,0), 
  "CONSTITUTE_NM" VARCHAR2(255 CHAR), 
  "DECLARATION_DT" TIMESTAMP (6), 
  "DELETED_BY" VARCHAR2(255 CHAR), 
  "DELETED_DT" TIMESTAMP (6), 
  "DIN" NUMBER(19,0), 
  "EMAIL_ID" VARCHAR2(255 CHAR), 
  "FROM_NSE" NUMBER(1,0), 
  "MEM_ID" NUMBER(19,0), 
  "MOBILE_NO" VARCHAR2(255 CHAR), 
  "NAME" VARCHAR2(255 CHAR), 
  "PAN" VARCHAR2(255 CHAR), 
  "PAN_STATUS" VARCHAR2(255 CHAR), 
  "PHONE_NUMBER" VARCHAR2(255 CHAR), 
  "ROLE" VARCHAR2(255 CHAR), 
  "SALUTATION" VARCHAR2(255 CHAR), 
  "SUBMISSION_DT" TIMESTAMP (6),
  "PAN_DOC_DMS_INDEX" VARCHAR2(255 CHAR), 
	"PAN_DOC_FILE_NAME" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );



CREATE TABLE "TBL_MEM_COM_APPLICATION_KMP" 
   (  "APP_ID" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "AP_DECLARATIONS" BLOB, 
  "AP_PROCESSING_FEES_BREAK_DOWN" BLOB, 
  "APP_APPROVAL_DT" TIMESTAMP (6), 
  "APP_COMPLETED_DATE" TIMESTAMP (6), 
  "APP_NO" VARCHAR2(255 CHAR), 
  "APP_START_DT" TIMESTAMP (6), 
  "APP_STATUS" NUMBER(10,0), 
  "APP_SUBMIT_DT" TIMESTAMP (6), 
  "ASSIGNED_ID" NUMBER(19,0), 
  "ASSIGNED_TYPE" VARCHAR2(255 CHAR), 
  "CID_PROCESSING_FEES" VARCHAR2(255 CHAR), 
  "CONTACT_ID" NUMBER(19,0), 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "MAIN_REQUEST" VARCHAR2(255 CHAR), 
  "MAKER_ASSIGNED_DT" TIMESTAMP (6), 
  "MEM_APPROVAL_DATE" TIMESTAMP (6), 
  "MEMBER_UNDERTAKING" VARCHAR2(255 CHAR), 
  "PAGE_ID" VARCHAR2(255 CHAR), 
  "SUB_REQUEST" VARCHAR2(255 CHAR), 
  "SUB_STATUS" NUMBER(10,0), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "WORKFLOW_ID" NUMBER(19,0), 
  "CHECKER_ID" NUMBER(19,0), 
  "MAKER_ID" NUMBER(19,0), 
  "MEM_ID" NUMBER(19,0), 
   PRIMARY KEY ("APP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "UK_JEUPFNYPVQF5J3VHNNL1YL71X" UNIQUE ("APP_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FKNAE8V5V0WHNM11F5SKULANF1H" FOREIGN KEY ("CHECKER_ID")
    REFERENCES "TBL_USER_MEM_COM" ("ID") ENABLE, 
   CONSTRAINT "FK86K97MI82Y6CFYWJHB8OPMD4C" FOREIGN KEY ("MAKER_ID")
    REFERENCES "TBL_USER_MEM_COM" ("ID") ENABLE, 
   CONSTRAINT "FKC4J4EELCIQ35Q84BKW8B9GI9W" FOREIGN KEY ("MEM_ID")
    REFERENCES "TBL_MEMBER_MASTER" ("MEM_ID") ENABLE
   );


CREATE TABLE "TBL_MTR_SYMBOL_NAME" 
   (  "SYMBOL_CODE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "SYMBOL_NAME" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("SYMBOL_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

CREATE TABLE "TBL_MTR_ERROR_CODE_MASTER" 
   (  "ERROR_CODE" VARCHAR2(255 CHAR) NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "ERROR_DESC" VARCHAR2(255 CHAR), 
   PRIMARY KEY ("ERROR_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

CREATE TABLE "TBL_PENALTY" 
   (	
    "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
	"CREATED_BY" VARCHAR2(255 CHAR), 
	"CREATED_DT" TIMESTAMP (6),
	"UPDATED_BY" VARCHAR2(255 CHAR),
	"UPDATED_DT" TIMESTAMP (6),
	"ANNEXURE_FILE_DMS_INDEX" VARCHAR2(255 CHAR),
	"ANNEXURE_FILE_NAME" VARCHAR2(255 CHAR),
	"APPROVAL_FILE_NAME" VARCHAR2(255 CHAR),
	"APPROVAL_NOTE_DMS_INDEX" VARCHAR2(255 CHAR),
	"INSPECTION_FILE_DMS_INDEX" VARCHAR2(255 CHAR),
	"INSPECTION_FILE_NAME" VARCHAR2(255 CHAR),
	"NOTIFY_MAKER_STATUS" NUMBER(1,0),
	"PENALTY_MONTH" NUMBER(10,0),
	"PENALTY_STATUS" NUMBER(10,0),
	"PENALTY_YEAR" NUMBER(10,0),
	"CHECKER_ID" NUMBER(19,0),
	"HO_MAKER_ID" NUMBER(19,0),
	"APP_ID" VARCHAR2(255 CHAR),
	"PENALTY_TYPE" VARCHAR2(10),
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
	 CONSTRAINT "FK1N2DP8LGBX705XCY118QV8BHA" FOREIGN KEY ("CHECKER_ID")
	  REFERENCES "TBL_USER_MEM_COM" ("ID") ENABLE, 
	 CONSTRAINT "FKCU7588BPNN8SKDFPTG2H5MX7E" FOREIGN KEY ("APP_ID")
	  REFERENCES "TBL_MEM_COM_APPLICATION_KMP" ("APP_ID") ENABLE
   );

   CREATE TABLE "TBL_PENALTY_MEMBER" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "AGENDA_MINUTES_DMS_INDEX" VARCHAR2(255 CHAR), 
  "AGENDA_MINUTES_FILE_NAME" VARCHAR2(255 CHAR), 
  "GENERATE_LETTER_STATUS" NUMBER(10,0), 
  "GENERATE_REVERSAL_LETTER_STATUS" NUMBER(10,0), 
  "NEW_PENALTY_AMT" FLOAT(126), 
  "NON_SUBMISSION_COUNT" NUMBER(10,0), 
  "NOTIFY_PENALTY_REVERSAL_STATUS" NUMBER(1,0), 
  "NOTIFY_PENALTY_STATUS" NUMBER(1,0), 
  "ORIGINAL_PENALTY_AMT" FLOAT(126), 
  "PENALTY_LETTER_DMS_INDEX" VARCHAR2(255 CHAR), 
  "PENALTY_LETTER_FILE_NAME" VARCHAR2(255 CHAR), 
  "PENALTY_REVERSAL_LETTER_DMS_INDEX" VARCHAR2(255 CHAR), 
  "PENALTY_REVERSAL_LETTER_FILE_NAME" VARCHAR2(255 CHAR), 
  "REASON_TYPE" NUMBER(10,0), 
  "REMARK" CLOB,
  "REVIEW_REASON_TYPE" NUMBER(10,0), 
  "REVIEW_STATUS" NUMBER(1,0), 
  "REVISED_AMT" FLOAT(126), 
  "MEMBER_ID" NUMBER(19,0), 
  "PENALTY_REC_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FKRDAQDF5V5V9VXECX7Y70E7581" FOREIGN KEY ("MEMBER_ID")
    REFERENCES "TBL_MEMBER_MASTER" ("MEM_ID") ENABLE, 
   CONSTRAINT "FKHYOR4P7157DOL59NIIBGF5QK7" FOREIGN KEY ("PENALTY_REC_ID")
    REFERENCES "TBL_PENALTY" ("ID") ENABLE
   );

   CREATE TABLE "TBL_PENALTY_REVIEW" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "CHECKER_COMMENTS_ANNEXURE_FILE" CLOB,
  "CHECKER_COMMENTS_NOTE" CLOB,
  "MAKER_COMMENTS_ANNEXURE_FILE" CLOB,
  "MAKER_COMMENTS_NOTE" CLOB,
  "REVIEW_STATUS" NUMBER(10,0), 
  "STATUS_ANNEXURE_FILE" VARCHAR2(255 CHAR),
  "STATUS_APPROVAL_NOTE" VARCHAR2(255 CHAR),
  "USER_TYPE" NUMBER(10,0), 
  "PENALTY_REC_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FK851XTTI3GHKMIDKW2NR3JGUU0" FOREIGN KEY ("PENALTY_REC_ID")
    REFERENCES "TBL_PENALTY" ("ID") ENABLE
   );

   CREATE TABLE "TBL_PENALTY_DOC_MASTER" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "PENALTY_DOC_INDEX" VARCHAR2(255 CHAR), 
  "PENALTY_DOC_TYPE_NAME" VARCHAR2(255 CHAR), 
  "PENALTY_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FKLRAHGYJYSGAE53QKD81JK7TB2" FOREIGN KEY ("PENALTY_ID")
    REFERENCES "TBL_PENALTY" ("ID") ENABLE
   );

CREATE TABLE "TBL_MTR_HO_MAKER" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "ACTIVE_ON" TIMESTAMP (6), 
  "DEACTIVE_ON" TIMESTAMP (6), 
  "HO_MAKER_STATUS" NUMBER(1,0), 
  "WORK_FLOW_ID" NUMBER(10,0), 
  "HO_MAKER_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FKC7U658AQVPO3DQHJ5HYTBFRFB" FOREIGN KEY ("HO_MAKER_ID")
    REFERENCES "TBL_USER_MEM_COM" ("ID") ENABLE
   );

CREATE TABLE "TBL_MTR_MRG_TRADING_REPORT" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "FINAL_REPORT_DMS_DOC_INDEX" VARCHAR2(255 CHAR), 
  "MRG_TRADING_FINAL_STATUS" NUMBER(1,0), 
  "MRG_TRADING_PROVISIONAL_STATUS" NUMBER(1,0), 
  "MTR_COUNTER_DATE" DATE, 
  "MTR_COUNTER_LATEST" NUMBER(10,0), 
  "MTR_COUNTER_TOTAL" NUMBER(10,0), 
  "NOTIFY_DAILY_SIGNOFF_STATUS" NUMBER(1,0), 
  "NOTIFY_MRG_TRADING_STATUS" NUMBER(1,0), 
  "PROVISIONAL_REPORT_DMS_DOC_INDEX" VARCHAR2(255 CHAR), 
  "REPORTING_DATE" DATE, 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

CREATE TABLE "TBL_MTR_SEBI_DAILY_STATUS" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "DAILY_FILE_STATUS" NUMBER(1,0), 
  "NIL_SUBMISSION_STATUS" NUMBER(1,0), 
  "NOTIFY_DAILY_FILE_STATUS" NUMBER(1,0), 
  "NOTIFY_NIL_STATUS" NUMBER(1,0), 
  "REPORTING_DATE" TIMESTAMP (6), 
  "SEBI_FILE_STATUS" NUMBER(1,0), 
  "MEMBER_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FKRE28MONE0KD66AJT6S9VKKAN8" FOREIGN KEY ("MEMBER_ID")
    REFERENCES "TBL_MEMBER_MASTER" ("MEM_ID") ENABLE
   );

CREATE TABLE "TBL_MTR_DAILY_FILE" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "BATCH_NO" NUMBER(10,0), 
  "DAILY_FILE_NAME" VARCHAR2(255 CHAR), 
  "DAILY_FILE_STATUS" NUMBER(1,0), 
  "DAILY_FILE_SUBMISSION_DATE" TIMESTAMP (6), 
  "DMS_DOC_INDEX" VARCHAR2(255 CHAR), 
  "DMS_RES_INDEX" VARCHAR2(255 CHAR), 
  "NIL_SUBMISSION_DATE" TIMESTAMP (6), 
  "NIL_SUBMISSION_STATUS" NUMBER(1,0), 
  "REPORTING_DATE" TIMESTAMP (6),
  "RESPONSE_FILE_NAME" VARCHAR2(255 CHAR), 
  "MEMBER_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "UKBQC333HM5IV4BPT62J6WHVNRG" UNIQUE ("MEMBER_ID", "REPORTING_DATE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FKD2EICK6SOX2KG9V0E69MXVQ0J" FOREIGN KEY ("MEMBER_ID")
    REFERENCES "TBL_MEMBER_MASTER" ("MEM_ID") ENABLE
   );

CREATE TABLE "TBL_MTR_DAILY_JOB_STATUS"
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
  "CREATED_BY" VARCHAR2(255 CHAR),
  "CREATED_DT" TIMESTAMP (6),
  "UPDATED_BY" VARCHAR2(255 CHAR),
  "UPDATED_DT" TIMESTAMP (6),
  "REPORTING_DATE" DATE,
  "LAST_RUN_START" TIMESTAMP (6),
  "LAST_RUN_END" TIMESTAMP (6),
  "RE_RUN_COUNTER" NUMBER(10,0),
  "DAILY_FILE_PROCESS_STATUS" CHAR(1 BYTE),
  "MRG_TRADING_REPORT_STATUS" CHAR(1 BYTE),
  "NSE_WEBSITE_PUBLISH_STATUS" CHAR(1 BYTE),
  "SEBI_FILE_TRANSFER_STATUS" CHAR(1 BYTE),
  "NSE_COMPLIANCE_NOTIFY_STATUS" CHAR(1 BYTE),
  "LAST_RUN_REMARK" CLOB,
   PRIMARY KEY ("ID")
   );

CREATE TABLE "TBL_MTR_MONTHLY_JOB_STATUS"
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE,
  "CREATED_BY" VARCHAR2(255 CHAR),
  "CREATED_DT" TIMESTAMP (6),
  "UPDATED_BY" VARCHAR2(255 CHAR),
  "UPDATED_DT" TIMESTAMP (6),
  "JOB_YEAR" NUMBER(4,0),
  "JOB_MONTH" NUMBER(2,0),
  "JOB_TYPE" CHAR(1 BYTE),
  "LAST_RUN_START" TIMESTAMP (6),
  "LAST_RUN_END" TIMESTAMP (6),
  "RE_RUN_COUNTER" NUMBER(10,0),
  "LAST_RUN_STATUS" CHAR(1 BYTE),
  "LAST_RUN_REMARK" CLOB,
   PRIMARY KEY ("ID")
   );

CREATE TABLE "TBL_MTR_MEMBER_LIST" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "COOLING_PERIOD_END_DATE" DATE, 
  "COOLING_PERIOD_START_DATE" DATE, 
  "ELIGIBLE_MEMBER_MTR_FROM" DATE, 
  "ELIGIBLE_MEMBER_MTR_STATUS" NUMBER(1,0), 
  "MEMBER_STATUS" VARCHAR2(255 CHAR), 
  "WITHDRAWAL_REASON" NUMBER(1,0), 
  "MEMBER_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FK828TQQ9WSKXAM6300WWEP9JJU" FOREIGN KEY ("MEMBER_ID")
    REFERENCES "TBL_MEMBER_MASTER" ("MEM_ID") ENABLE
   );

CREATE TABLE "TBL_MTR_ERROR_DAILY_FILE" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "ERROR_CODE" VARCHAR2(255 CHAR), 
  "MTR_FILE_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
   );

CREATE TABLE "TBL_MTR_DAILY_FILE_VALIDATION" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "BATCH_NO" NUMBER(10,0), 
  "DAILY_FILE_NAME" VARCHAR2(255 CHAR), 
  "DAILY_FILE_STATUS" NUMBER(1,0), 
  "DAILY_FILE_SUBMISSION_DATE" TIMESTAMP (6), 
  "DMS_DOC_INDEX" VARCHAR2(255 CHAR), 
  "DMS_RES_INDEX" VARCHAR2(255 CHAR), 
  "ERROR_CODE_FILE_DMS_INDEX" VARCHAR2(255 CHAR), 
  "ERROR_CODE_FILE_NAME" VARCHAR2(255 CHAR), 
  "REPORTING_DATE" TIMESTAMP (6), 
  "RESPONSE_FILE_NAME" VARCHAR2(255 CHAR), 
  "MEMBER_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FKOYFJJCOA791D0B2GI5CK3R02R" FOREIGN KEY ("MEMBER_ID")
    REFERENCES "TBL_MEMBER_MASTER" ("MEM_ID") ENABLE
   );

CREATE TABLE "TBL_MTR_COLLATERALS_SCRIPS_DETAIL_RECORD" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "AMOUNT_END_DAY" FLOAT(126), 
  "CATEGORY_OF_HOLDING" NUMBER(1,0), 
  "CLIENT_NAME" VARCHAR2(255 CHAR), 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "ERROR_CODES" VARCHAR2(255 CHAR), 
  "PAN" VARCHAR2(255 CHAR), 
  "QUANTITY_END_DAY" NUMBER(10,0), 
  "RECORD_TYPE" NUMBER(10,0), 
  "ROW_STATUS" NUMBER(1,0), 
  "SERIES" VARCHAR2(255 CHAR), 
  "STOCK_EXCHANGE" VARCHAR2(255 CHAR), 
  "SUBMISSION_DATE" DATE, 
  "SYMBOL" VARCHAR2(255 CHAR), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "MTR_FILE_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FKABR04W0SFQVHDKGX244R6PPTS" FOREIGN KEY ("MTR_FILE_ID")
    REFERENCES "TBL_MTR_DAILY_FILE" ("ID") ENABLE
   );

CREATE TABLE "TBL_MTR_COLLATERALS_SUMMARY_RECORD" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "ERROR_CODES" VARCHAR2(255 CHAR), 
  "RECORD_TYPE" NUMBER(10,0), 
  "ROW_STATUS" NUMBER(1,0), 
  "SUBMISSION_DATE" DATE, 
  "COLLATERAL_CASH" FLOAT(126), 
  "COLLATERAL_CASH_EQUIVALENT" FLOAT(126), 
  "COLLATERAL_SCRIPS" FLOAT(126), 
  "MTR_FILE_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FKQ3MC17LLOXVY75VRHU4S3PRF9" FOREIGN KEY ("MTR_FILE_ID")
    REFERENCES "TBL_MTR_DAILY_FILE" ("ID") ENABLE
   );

CREATE TABLE "TBL_MTR_DETAIL_RECORD" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CATEGORY_OF_HOLDING" NUMBER(1,0), 
  "CLIENT_NAME" VARCHAR2(255 CHAR), 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "ERROR_CODES" VARCHAR2(255 CHAR), 
  "FUNDED_AMOUNT_BEGIN_DAY" FLOAT(126), 
  "FUNDED_AMOUNT_DURING_DAY" FLOAT(126), 
  "FUNDED_AMOUNT_END_DAY" FLOAT(126), 
  "FUNDED_AMOUNT_LIQUIDATED_DURING_DAY" FLOAT(126), 
  "FUNDED_QUANTITY_BEGIN_DAY" NUMBER(10,0), 
  "FUNDED_QUANTITY_DURING_DAY" NUMBER(10,0), 
  "FUNDED_QUANTITY_END_DAY" NUMBER(10,0), 
  "FUNDED_QUANTITY_LIQUIDATED_DURING_DAY" NUMBER(10,0), 
  "PAN" VARCHAR2(255 CHAR), 
  "RECORD_TYPE" NUMBER(10,0), 
  "ROW_STATUS" NUMBER(1,0), 
  "SERIES" VARCHAR2(255 CHAR), 
  "STOCK_EXCHANGE" VARCHAR2(255 CHAR), 
  "SUBMISSION_DATE" DATE, 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "MTR_FILE_ID" NUMBER(19,0), 
  "SYMBOL" VARCHAR2(255 CHAR), 
  "HASH_CODE_CLIENT_NAME_PAN_SYMBOL" NUMBER(10,0),
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FK924CO6DXC3M5U09SDWORWOREI" FOREIGN KEY ("MTR_FILE_ID")
    REFERENCES "TBL_MTR_DAILY_FILE" ("ID") ENABLE, 
   CONSTRAINT "FK1Q7RPMW56JQWRLHYU32SMSM3N" FOREIGN KEY ("SYMBOL")
    REFERENCES "TBL_MTR_SYMBOL_NAME" ("SYMBOL_CODE") ENABLE
   );

CREATE INDEX TBL_MTR_DETAIL_RECORD_MTR_FILE_ID_HASH_CODE_CLIENT_NAME_PAN_SYMBOL ON TBL_MTR_DETAIL_RECORD(MTR_FILE_ID, HASH_CODE_CLIENT_NAME_PAN_SYMBOL);

CREATE TABLE "TBL_MTR_SUMMARY_RECORD" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "AMOUNT_FUNDED" FLOAT(126), 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "ERROR_CODES" VARCHAR2(255 CHAR), 
  "LENDER_CATEGORY" NUMBER(10,0), 
  "LENDER_NAME" VARCHAR2(255 CHAR), 
  "RECORD_TYPE" NUMBER(10,0), 
  "ROW_STATUS" NUMBER(1,0), 
  "SUBMISSION_DATE" DATE, 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "MTR_FILE_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FK1MJVV6E3HOXWMJWUSKJGEJJ5I" FOREIGN KEY ("MTR_FILE_ID")
    REFERENCES "TBL_MTR_DAILY_FILE" ("ID") ENABLE
   );

CREATE TABLE "TBL_MTR_CONTROL_RECORD" 
   (  "ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE, 
  "CREATED_BY" VARCHAR2(255 CHAR), 
  "CREATED_DT" TIMESTAMP (6), 
  "UPDATED_BY" VARCHAR2(255 CHAR), 
  "UPDATED_DT" TIMESTAMP (6), 
  "ERROR_CODES" VARCHAR2(255 CHAR), 
  "RECORD_TYPE" NUMBER(10,0), 
  "ROW_STATUS" NUMBER(1,0), 
  "SUBMISSION_DATE" DATE, 
  "BATCH_DATE" DATE, 
  "BATCH_NUMBER" NUMBER(10,0),
  "FILE_TYPE" VARCHAR2(255 CHAR), 
  "MEMBER_CODE" VARCHAR2(255 CHAR), 
  "TOTAL_AMOUNT_FUNDED" FLOAT(126), 
  "TOTAL_DETAIL_RECORDS" NUMBER(10,0), 
  "TOTAL_SUMMARY_RECORDS" NUMBER(10,0), 
  "MTR_FILE_ID" NUMBER(19,0), 
   PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE, 
   CONSTRAINT "FKHVHCAYOEC8WR0DH50BTBLG4WI" FOREIGN KEY ("MTR_FILE_ID")
    REFERENCES "TBL_MTR_DAILY_FILE" ("ID") ENABLE
   );
   
CREATE TABLE "TBL_KMP_APPLI_DTLS "
	(  "APP_ID" NUMBER(19,0) GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 
  START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  NOT NULL ENABLE
, "MEMBER_NAME" VARCHAR2(50) NOT NULL 
, "MEMBER_CODE" NUMBER NOT NULL 
, "MEMBER_TYPE" VARCHAR2(20) NOT NULL 
, "REQUEST_TYPE" VARCHAR2(20) NOT NULL 
, "STATUS" VARCHAR2(20) NOT NULL 
, "APPLICATION_STARTED_ON" TIMESTAMP 
, "APPLICATION_SUBMITTED_ON" TIMESTAMP 
, "REMARKS" VARCHAR2(1020) 
, "CREATED_BY" VARCHAR2(255 CHAR)
, "CREATED_DT" TIMESTAMP (6) 
, "UPDATED_BY" VARCHAR2(255 CHAR)
, "UPDATED_DT" TIMESTAMP (6)
, "DELETED_BY" VARCHAR2(255 CHAR)
, "DELETED_DATE" TIMESTAMP (6)
, PRIMARY KEY ("APP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  TABLESPACE "CMSTR_TABLESPACE"  ENABLE
);
